- link:
    ~/.oh-my-zsh/custom/plugins:
      force: true
      path: zsh/plugins
    ~/.oh-my-zsh/custom/themes:
      force: true
      path: zsh/themes
    ~/.zsh:
    ~/.p10k.zsh:
    ~/.zshrc:
      force: true
<<<<<<< HEAD
    ~/.oh-my-zsh:
      force: true
      path: zsh/omz
=======
>>>>>>> 49cddaa0ab2ff9e35c5ba92adea8181491a6bfd4
