- defaults:
    link:
      create: true
      relink: true

- clean: [
    '~',
    '~/.config'
]
- link:
    ~/.dotfiles: ""
    ~/.shell:
    ~/.vim:
    ~/.oh-my-zsh/custom/plugins:
      force: true
      path: zsh/plugins
    ~/.oh-my-zsh/custom/themes:
      force: true
      path: zsh/themes
    ~/.zsh:
    ~/.p10k.zsh:
    ~/.vimrc:
    ~/.zshrc:
      force: true
- shell:
    - chsh -s $(which zsh) $(whoami)
    - git submodule sync --recursive
    - git submodule update --init --recursive --force --remote
